name: insights_staff_app
publish_to: "none"
description: Insights Club Staff App
version: 1.2.1+121

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  go_router: ^14.6.2
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.2
  mobile_scanner: ^6.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/insights_club_logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/insights_club_logo.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/images/insights_club_logo.png
    background_color: "#0D0F14"
    theme_color: "#FF7A1A"

flutter_native_splash:
  color: "#0D0F14"
  image: assets/images/insights_club_logo.png
  android: true
  ios: false
  web: true
